# =====================================================================================
# Finetuning Script for Independently Distilled Models
#
# This script loads the lightweight multi-modal components distilled by 'distill_nosyc.py'
# and finetunes them end-to-end on the downstream classification task.
#
# A key feature of this workflow is the use of preprocessed graph data ('.pt' files)
# generated by 'preprocess.py', which speeds up data loading during training.
#
# Author: [Haoqian Song, Haoran Yin, Fuwen Zhao]
# Date: September 18, 2025
# =====================================================================================

import os
import pandas as pd
from PIL import Image
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader as TorchDataLoader

from transformers import BertModel, CLIPVisionModel, CLIPProcessor, BertTokenizer
from sklearn.metrics import accuracy_score, f1_score, precision_recall_fscore_support

try:
    from torch_geometric.data import Batch
    from torch_geometric.nn import GATConv, global_mean_pool
except ImportError:
    print("❌ Error: torch_geometric library not found or not installed correctly.")
    exit()

# ================== Configuration ==================
CSV_PATH = './datasets/TextClassification/toutiao/toutiao_622.csv'
PREPROCESSED_DATA_DIR = './processed_data' # Directory containing data_{idx}.pt files
PROJECT_ROOT = '/workspace'                # Base path for image paths in the CSV
CONTENT_MODEL_PATH = './lightweight_content_model_distilled'
VISION_MODEL_PATH  = './lightweight_vision_model_distilled' # Must contain visual_projection.pt
GAT_MODEL_PATH     = './lightweight_gat_model.pth'

# Note: This config must match the STUDENT_CONFIG_GAT from the distillation script
GAT_CONFIG = {"in_channels": 100, "hidden_channels": 64, "num_layers": 1, "out_channels": 64, "heads": 2}
NUM_CLASSES = 3
BATCH_SIZE = 32
NUM_EPOCHS = 10
LEARNING_RATE = 2e-5
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
FINETUNED_MODEL_SAVE_PATH = "./final_lightweight_model_nosyc.pth"
# ===================================================

class GATModel(nn.Module):
    """Graph Attention Network model. Architecture must match the saved student model."""
    def __init__(self, in_channels, hidden_channels, num_layers, out_channels, heads):
        super().__init__()
        self.convs = nn.ModuleList()
        self.convs.append(GATConv(in_channels, hidden_channels, heads=heads))
        for _ in range(num_layers - 1):
            self.convs.append(GATConv(hidden_channels * heads, hidden_channels, heads=heads))
        self.fc = nn.Linear(hidden_channels * heads, out_channels)

    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        for conv in self.convs:
            x = conv(x, edge_index)
            x = F.elu(x)
        x = global_mean_pool(x, batch)
        return self.fc(x)

class FinalDataset(Dataset):
    """Loads data from CSV, preprocessed graph files (data_{idx}.pt), and images."""
    def __init__(self, csv_path, preprocessed_dir, project_root):
        self.project_root = project_root
        self.preprocessed_dir = preprocessed_dir
        self.df = pd.read_csv(csv_path, header=None, names=['label', 'title', 'content', 'image_path'])

        # Filter the dataframe to only include samples with corresponding preprocessed graph files
        self.valid_indices = [
            idx for idx in range(len(self.df))
            if os.path.exists(os.path.join(self.preprocessed_dir, f'data_{idx}.pt'))
        ]

    def __len__(self):
        return len(self.valid_indices)

    def __getitem__(self, index):
        # Map the dataset index to the original dataframe index
        idx = self.valid_indices[index]
        row = self.df.iloc[idx]
        label, content, path = int(row['label']), str(row['content']), str(row['image_path'])

        # Load image (use a white placeholder for missing/corrupt images)
        image = Image.new('RGB', (224, 224), color='white')
        if path and path.lower() != 'nan':
            try:
                full_path = os.path.join(self.project_root, path)
                if os.path.exists(full_path):
                    image = Image.open(full_path).convert("RGB")
            except Exception:
                pass

        # Load the preprocessed graph data, detach from graph, and ensure correct dtype
        graph_data_path = os.path.join(self.preprocessed_dir, f'data_{idx}.pt')
        graph_data = torch.load(graph_data_path, map_location='cpu')
        if hasattr(graph_data, "x") and graph_data.x is not None:
            graph_data.x = graph_data.x.detach().requires_grad_(False).to(torch.float32)
        if hasattr(graph_data, "edge_index") and graph_data.edge_index is not None:
            graph_data.edge_index = graph_data.edge_index.to(torch.long).contiguous()

        return content, image, label, graph_data

def collate_fn_final(batch):
    """Custom collate function to batch multi-modal data."""
    contents, images, labels, graph_data_list = zip(*batch)
    batched_graph = Batch.from_data_list(list(graph_data_list))
    return list(contents), list(images), torch.tensor(list(labels), dtype=torch.long), batched_graph

class FinalLightweightModel(nn.Module):
    """Final model assembling the lightweight BERT, CLIP-Vision, and GAT components."""
    def __init__(self, content_path, vision_path, gat_path, num_classes):
        super().__init__()
        # Text Component
        self.content_model = BertModel.from_pretrained(content_path)

        # Vision Component + Projection Layer
        self.vision_model = CLIPVisionModel.from_pretrained(vision_path)
        vision_proj = nn.Linear(self.vision_model.config.hidden_size, 512, bias=False)
        vision_proj.load_state_dict(torch.load(os.path.join(vision_path, 'visual_projection.pt'), map_location='cpu'))
        self.visual_projection = vision_proj

        # GAT Component
        self.gat_model = GATModel(**GAT_CONFIG)
        self.gat_model.load_state_dict(torch.load(gat_path, map_location='cpu'))

        # Classifier Head
        classifier_input_dim = self.content_model.config.hidden_size + 512 + GAT_CONFIG["out_channels"]
        self.classifier = nn.Sequential(
            nn.Linear(classifier_input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, content_inputs, pixel_values, graph_batch):
        content_feature = self.content_model(**content_inputs).pooler_output
        vision_outputs = self.vision_model(pixel_values=pixel_values)
        image_feature = self.visual_projection(vision_outputs.pooler_output)
        gat_feature = self.gat_model(graph_batch)
        combined_features = torch.cat([content_feature, image_feature, gat_feature], dim=1)
        return self.classifier(combined_features)

def main():
    print(f"--- Starting Final Model Finetuning (Device: {DEVICE}) ---")
    content_tokenizer = BertTokenizer.from_pretrained(CONTENT_MODEL_PATH)
    vision_processor = CLIPProcessor.from_pretrained(VISION_MODEL_PATH)

    # Data setup
    dataset = FinalDataset(CSV_PATH, PREPROCESSED_DATA_DIR, PROJECT_ROOT)
    train_loader = TorchDataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn_final, num_workers=4)

    # Model setup
    model = FinalLightweightModel(CONTENT_MODEL_PATH, VISION_MODEL_PATH, GAT_MODEL_PATH, NUM_CLASSES).to(DEVICE)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)

    # Weighted loss for class imbalance (based on valid samples)
    valid_labels = dataset.df.iloc[dataset.valid_indices]['label']
    class_counts = valid_labels.value_counts().sort_index()
    if not class_counts.empty and len(class_counts) > 1:
        weights = class_counts.sum() / (len(class_counts) * class_counts)
        class_weights = torch.tensor(weights.values, dtype=torch.float).to(DEVICE)
        loss_fn = nn.CrossEntropyLoss(weight=class_weights)
        print("Weighted loss function enabled to handle class imbalance.\n")
    else:
        loss_fn = nn.CrossEntropyLoss()
        print("Warning: Could not compute class weights. Using standard loss function.\n")

    # Training and evaluation loop
    for epoch in range(NUM_EPOCHS):
        model.train()
        pbar_train = tqdm(train_loader, desc=f"Finetuning Epoch {epoch + 1}/{NUM_EPOCHS}")
        for batch in pbar_train:
            contents, images, labels, graph_batch = batch
            content_inputs = content_tokenizer(contents, return_tensors='pt', max_length=256, padding='max_length', truncation=True).to(DEVICE)
            pixel_values = vision_processor(images=images, return_tensors='pt')['pixel_values'].to(DEVICE)
            graph_batch = graph_batch.to(DEVICE)
            labels = labels.to(DEVICE)

            logits = model(content_inputs, pixel_values, graph_batch)
            loss = loss_fn(logits, labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            pbar_train.set_postfix({"loss": loss.item()})

        # ====== Evaluation at the end of each epoch ======
        model.eval()
        all_preds, all_labels = [], []
        # Create a new loader for evaluation to ensure it's not shuffled
        eval_loader = TorchDataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn_final, num_workers=4)
        with torch.no_grad():
            for batch in tqdm(eval_loader, desc="Evaluating"):
                contents, images, labels, graph_batch = batch
                content_inputs = content_tokenizer(contents, return_tensors='pt', max_length=256, padding='max_length', truncation=True).to(DEVICE)
                pixel_values = vision_processor(images=images, return_tensors='pt')['pixel_values'].to(DEVICE)
                graph_batch = graph_batch.to(DEVICE)
                labels = labels.to(DEVICE)

                logits = model(content_inputs, pixel_values, graph_batch)
                preds = torch.argmax(logits, dim=1)

                all_preds.extend(preds.cpu().numpy().tolist())
                all_labels.extend(labels.cpu().numpy().tolist())

        acc = accuracy_score(all_labels, all_preds)
        f1_macro = f1_score(all_labels, all_preds, average='macro', zero_division=0)
        
        # Calculate per-class metrics
        prec, rec, f1_per_class, support = precision_recall_fscore_support(
            all_labels, all_preds, labels=[0, 1, 2], zero_division=0
        )

        print(f"\n--- Epoch {epoch+1} Evaluation Results ---")
        print(f"  Overall Accuracy: {acc:.4f}")
        print(f"  Macro F1-Score  : {f1_macro:.4f}")
        print("  --- Per-Class Metrics ---")
        for i in range(len(prec)):
            print(f"    Class {i} | P={prec[i]:.4f} R={rec[i]:.4f} F1={f1_per_class[i]:.4f} | Support={support[i]}")
        print("-" * 30)

    # Save the final model weights
    torch.save(model.state_dict(), FINETUNED_MODEL_SAVE_PATH)
    print(f"\n--- Finetuning Complete! Final model saved to: '{FINETUNED_MODEL_SAVE_PATH}' ---")


if __name__ == "__main__":
    main()